// REGISTER USER
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

// GET TOKEN
export const OBTAIN_TOKEN_START = "OBTAIN_TOKEN_START";
export const OBTAIN_TOKEN_FAIL = "OBTAIN_TOKEN_FAIL";
export const OBTAIN_TOKEN_SUCESS = "OBTAIN_TOKEN_SUCESS";

// Login
export const IS_LOGGED_IN = "IS_LOGGED_IN";
