export const bookingData = [
  {
    orderNumber: 5555,
    partnerStatusAssigned: "Assigning Professional",
    partnerImage: "assets/images/bookings-page-profile.png",
    partnerName: "Akash",
    bookingDateAndTime: " 20th April, 9-11 AM",
    issueDevice: "Air Conditioner",
    issueType: "Less Cooling/No Cooling",
    partnerAssigningOTP: 0,
  },
  // {
  //   orderNumber: 5555,
  //   partnerStatusAssigned: "Partner Assigned",
  //   partnerImage: "assets/images/bookings-page-profile.png",
  //   partnerName: "Akash",
  //   bookingDateAndTime: " 20th April, 9-11 AM",
  //   issueDevice: "Air Conditioner",
  //   issueType: "Less Cooling/No Cooling",
  //   partnerAssigningOTP: 1,
  //   OTP: "1111",
  // },
  // {
  //   orderNumber: 5555,
  //   partnerStatusAssigned: "Men At Work",
  //   partnerImage: "assets/images/bookings-page-profile.png",
  //   partnerName: "Akash",
  //   bookingDateAndTime: " 20th April, 9-11 AM",
  //   issueDevice: "Air Conditioner",
  //   issueType: "Less Cooling/No Cooling",
  //   partnerAssigningOTP: 2,
  // },
  // {
  //   orderNumber: 5555,
  //   partnerStatusAssigned: "Job Completed",
  //   partnerImage: "assets/images/bookings-page-profile.png",
  //   partnerName: "Akash",
  //   bookingDateAndTime: " 20th April, 9-11 AM",
  //   issueDevice: "Air Conditioner",
  //   issueType: "Less Cooling/No Cooling",
  //   partnerAssigningOTP: 3,
  // },
];
