export const issueData = [
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
  {
    issueImage: "assets/images/issue-images.png",
    issueName: "Issue Name",
    issueAlt: "Issue Name",
    issueOfferPrice: 1000,
    issueOriginalPrice: 2000,
    serviceTime: "Lorem Ipsum",
    warranty: "Lorem Ipsum",
    serviceType: "Lorem Ipsum",
    href: "#",
    addToCart: "#",
    buttonName: "Add to Cart",
  },
];
