// Home Page

// city
export const GET_CITY_START = "GET_CITY_START";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAIL = "GET_CITY_FAIL";

// Testimonials Home
export const GET_HOME_TESTIMONIALS_START = "GET_HOME_TESTIMONIALS_START";
export const GET_HOME_TESTIMONIALS_SUCCESS = "GET_HOME_TESTIMONIALS_SUCCESS";
export const GET_HOME_TESTIMONIALS_FAIL = "GET_HOME_TESTIMONIALS_FAIL";

// Hero Section Home
export const GET_HOME_HERO_SECTION_START = "GET_HOME_HERO_SECTION_START";
export const GET_HOME_HERO_SECTION_SUCCESS = "GET_HOME_HERO_SECTION_SUCCESS";
export const GET_HOME_HERO_SECTION_FAIL = "GET_HOME_HERO_SECTION_FAIL";

// Issue page
export const GET_CATEGORY_ID_SUCCESS = "GET_CATEGORY_ID_SUCCESS";
export const GET_BRAND_ID_SUCCESS = "GET_BRAND_ID_SUCCESS";
export const GET_MODEL_ID_SUCCESS = "GET_MODEL_ID_SUCCESS";

// home appliances
export const GET_HOME_APPLIANCES_START = "GET_HOME_APPLIANCES_START";
export const GET_HOME_APPLIANCES_SUCCESS = "GET_HOME_APPLIANCES_SUCCESS";
export const GET_HOME_APPLIANCES_FAIL = "GET_HOME_APPLIANCES_FAIL";

export const SELECT_HOME_APPLIANCES_START = "SELECT_HOME_APPLIANCES_START";
export const SELECT_HOME_APPLIANCES_SUCCESS = "SELECT_HOME_APPLIANCES_SUCCESS";
export const SELECT_HOME_APPLIANCES_FAIL = "SELECT_HOME_APPLIANCES_FAIL";

// home appliances models
export const GET_HOME_APPLIANCES_MODELS_START =
  "GET_HOME_APPLIANCES_MODELS_START";
export const GET_HOME_APPLIANCES_MODELS_SUCCESS =
  "GET_HOME_APPLIANCES_MODELS_SUCCESS";
export const GET_HOME_APPLIANCES_MODELS_FAIL =
  "GET_HOME_APPLIANCES_MODELS_FAIL";

export const SELECT_HOME_APPLIANCES_MODELS_SUCCESS =
  "SELECT_HOME_APPLIANCES_MODELS_SUCCESS";
export const SELECT_HOME_APPLIANCES_MODELS_START =
  "SELECT_HOME_APPLIANCES_MODELS_START";
export const SELECT_HOME_APPLIANCES_MODELS_FAIL =
  "SELECT_HOME_APPLIANCES_MODELS_FAIL";

//home appliances issues
export const GET_HOME_APPLIANCES_ISSUES_START =
  "GET_HOME_APPLIANCES_ISSUES_START";
export const GET_HOME_APPLIANCES_ISSUES_SUCCESS =
  "GET_HOME_APPLIANCES_ISSUES_SUCCESS";
export const GET_HOME_APPLIANCES_ISSUES_FAIL =
  "GET_HOME_APPLIANCES_ISSUES_FAIL";

export const SELECT_HOME_APPLIANCES_ISSUES_START =
  "SELECT_HOME_APPLIANCES_ISSUES_START";
export const SELECT_HOME_APPLIANCES_ISSUES_SUCCESS =
  "SELECT_HOME_APPLIANCES_ISSUES_SUCCESS";
export const SELECT_HOME_APPLIANCES_ISSUES_FAIL =
  "SELECT_HOME_APPLIANCES_ISSUES_FAIL";

// personal gadgets
export const GET_PERSONAL_GADGETS_START = "GET_PERSONAL_GADGETS_START";
export const GET_PERSONAL_GADGETS_SUCCESS = "GET_PERSONAL_GADGETS_SUCCESS";
export const GET_PERSONAL_GADGETS_FAIL = "GET_PERSONAL_GADGETS_FAIL";

export const SELECT_PERSONAL_GADGETS_START = "SELECT_PERSONAL_GADGETS_START";
export const SELECT_PERSONAL_GADGETS_SUCCESS =
  "SELECT_PERSONAL_GADGETS_SUCCESS";
export const SELECT_PERSONAL_GADGETS_FAIL = "SELECT_PERSONAL_GADGETS_FAIL";

// Personal Brands
export const GET_PERSONAL_BRANDS_START = "GET_PERSONAL_BRANDS_START";
export const GET_PERSONAL_BRANDS_SUCCESS = "GET_PERSONAL_BRANDS_SUCCESS";
export const GET_PERSONAL_BRANDS_FAIL = "GET_PERSONAL_BRANDS_FAIL";

export const SELECT_PERSONAL_BRANDS_START = "SELECT_PERSONAL_BRANDS_START";
export const SELECT_PERSONAL_BRANDS_SUCCESS = "SELECT_PERSONAL_BRANDS_SUCCESS";
export const SELECT_PERSONAL_BRANDS_FAIL = "SELECT_PERSONAL_BRANDS_FAIL";

// Personal Models
export const GET_PERSONAL_MODELS_START = "GET_PERSONAL_MODELS_START";
export const GET_PERSONAL_MODELS_SUCCESS = "GET_PERSONAL_MODELS_SUCCESS";
export const GET_PERSONAL_MODELS_FAIL = "GET_PERSONAL_MODELS_FAIL";

export const SELECT_PERSONAL_MODELS_START = "SELECT_PERSONAL_MODELS_START";
export const SELECT_PERSONAL_MODELS_SUCCESS = "SELECT_PERSONAL_MODELS_SUCCESS";
export const SELECT_PERSONAL_MODELS_FAIL = "SELECT_PERSONAL_MODELS_FAIL";

//personal issues
export const GET_PERSONAL_GADGETS_ISSUES_START =
  "GET_PERSONAL_GADGETS_ISSUES_START";
export const GET_PERSONAL_GADGETS_ISSUES_SUCCESS =
  "GET_PERSONAL_GADGETS_ISSUES_SUCCESS";
export const GET_PERSONAL_GADGETS_ISSUES_FAIL =
  "GET_PERSONAL_GADGETS_ISSUES_FAIL";

export const SELECT_PERSONAL_GADGETS_ISSUES_SUCCESS =
  "SELECT_PERSONAL_GADGETS_ISSUES_SUCCESS";
export const SELECT_PERSONAL_GADGETS_ISSUES_START =
  "SELECT_PERSONAL_GADGETS_ISSUES_START";
export const SELECT_PERSONAL_GADGETS_ISSUES_FAIL =
  "SELECT_PERSONAL_GADGETS_ISSUES_FAIL";

// Cart
export const FETCH_FROM_CART_START = "FETCH_FROM_CART_START";
export const FETCH_FROM_CART_COMPLETE = "FETCH_FROM_CART_COMPLETE";
export const FETCH_FROM_CART_FAIL = "FETCH_FROM_CART_FAIL"

export const ADD_OR_REMOVE_CART_START = "ADD_OR_REMOVE_CART_START";
export const ADD_OR_REMOVE_CART_SUCCESS = "ADD_OR_REMOVE_CART_SUCCESS";
export const ADD_OR_REMOVE_CART_FAIL = "ADD_OR_REMOVE_CART_FAIL";

// Coupons
export const GET_VALID_COUPONS_SUCCESS = "GET_VALID_COUPONS_SUCCESS";
export const GET_COUPONS_FAIL = "GET_COUPONS_FAIL";

export const APPLY_COUPONS_SUCCESS = "APPLY_COUPONS_SUCCESS";

export const REMOVE_COUPONS_START = "REMOVE_COUPONS_START";
export const REMOVE_COUPONS_SUCCESS = "REMOVE_COUPONS_SUCCESS";

// Offers
export const GET_OFFERS_HOME_START = "GET_OFFERS_HOME_START";
export const GET_OFFERS_HOME_SUCCESS = "GET_OFFERS_HOME_SUCCESS";
export const GET_OFFERS_HOME_FAIL = "GET_OFFERS_HOME_FAIL";

// Offers by Category
export const GET_OFFERS_BY_CATEGORY_START = "GET_OFFERS_BY_CATEGORY_START";
export const GET_OFFERS_BY_CATEGORY_SUCCESS = "GET_OFFERS_BY_CATEGORY_SUCCESS";
export const GET_OFFERS_BY_CATEGORY_FAIL = "GET_OFFERS_BY_CATEGORY_FAIL";

// Offers by Brands
export const GET_OFFERS_BY_BRANDS_START = "GET_OFFERS_BY_BRANDS_START";
export const GET_OFFERS_BY_BRANDS_SUCCESS = "GET_OFFERS_BY_BRANDS_SUCCESS";
export const GET_OFFERS_BY_BRANDS_FAIL = "GET_OFFERS_BY_BRANDS_FAIL";

// Offers by Models
export const GET_OFFERS_BY_MODELS_START = "GET_OFFERS_BY_MODELS_START";
export const GET_OFFERS_BY_MODELS_SUCCESS = "GET_OFFERS_BY_MODELS_SUCCESS";
export const GET_OFFERS_BY_MODELS_FAIL = "GET_OFFERS_BY_MODELS_FAIL";

// Info by Category
export const GET_INFORMATION_BY_CATEGORY_START =
  "GET_INFORMATION_BY_CATEGORY_START";
export const GET_INFORMATION_BY_CATEGORY_SUCCESS =
  "GET_INFORMATION_BY_CATEGORY_SUCCESS";
export const GET_INFORMATION_BY_CATEGORY_FAIL =
  "GET_INFORMATION_BY_CATEGORY_FAIL";

// Info by Brands
export const GET_INFORMATION_BY_BRANDS_START =
  "GET_INFORMATION_BY_BRANDS_START";
export const GET_INFORMATION_BY_BRANDS_SUCCESS =
  "GET_INFORMATION_BY_BRANDS_SUCCESS";
export const GET_INFORMATION_BY_BRANDS_FAIL = "GET_INFORMATION_BY_BRANDS_FAIL";

// Info by Models
export const GET_INFORMATION_BY_MODELS_START =
  "GET_INFORMATION_BY_MODELS_START";
export const GET_INFORMATION_BY_MODELS_SUCCESS =
  "GET_INFORMATION_BY_MODELS_SUCCESS";
export const GET_INFORMATION_BY_MODELS_FAIL = "GET_INFORMATION_BY_MODELS_FAIL";

// FAQ by Category
export const GET_FAQ_BY_CATEGORY_START = "GET_FAQ_BY_CATEGORY_START";
export const GET_FAQ_BY_CATEGORY_SUCCESS = "GET_FAQ_BY_CATEGORY_SUCCESS";
export const GET_FAQ_BY_CATEGORY_FAIL = "GET_FAQ_BY_CATEGORY_FAIL";

// FAQ BY Brands
export const GET_FAQ_BY_BRANDS_START = "GET_FAQ_BY_BRANDS_START";
export const GET_FAQ_BY_BRANDS_SUCCESS = "GET_FAQ_BY_BRANDS_SUCCESS";
export const GET_FAQ_BY_BRANDS_FAIL = "GET_FAQ_BY_BRANDS_FAIL";

// FAQ BY Models
export const GET_FAQ_BY_MODELS_START = "GET_FAQ_BY_MODELS_START";
export const GET_FAQ_BY_MODELS_SUCCESS = "GET_FAQ_BY_MODELS_SUCCESS";
export const GET_FAQ_BY_MODELS_FAIL = "GET_FAQ_BY_MODELS_FAIL";

// Testimonials by Category
export const GET_TESTIMONIALS_BY_CATEGORY_START =
  "GET_TESTIMONIALS_BY_CATEGORY_START";
export const GET_TESTIMONIALS_BY_CATEGORY_SUCCESS =
  "GET_TESTIMONIALS_BY_CATEGORY_SUCCESS";
export const GET_TESTIMONIALS_BY_CATEGORY_FAIL =
  "GET_TESTIMONIALS_BY_CATEGORY_FAIL_FAIL";

// Testimonials by Brands
export const GET_TESTIMONIALS_BY_BRANDS_START =
  "GET_TESTIMONIALS_BY_BRANDS_START";
export const GET_TESTIMONIALS_BY_BRANDS_SUCCESS =
  "GET_TESTIMONIALS_BY_BRANDS_SUCCESS";
export const GET_TESTIMONIALS_BY_BRANDS_FAIL =
  "GET_TESTIMONIALS_BY_BRANDS_FAIL";

// Testimonials by Models
export const GET_TESTIMONIALS_BY_MODELS_START =
  "GET_TESTIMONIALS_BY_MODELS_START";
export const GET_TESTIMONIALS_BY_MODELS_SUCCESS =
  "GET_TESTIMONIALS_BY_MODELS_SUCCESS";
export const GET_TESTIMONIALS_BY_MODELS_FAIL =
  "GET_TESTIMONIALS_BY_MODELS_FAIL";

// Hero Section by Category
export const GET_HERO_BY_CATEGORY_START = "GET_HERO_BY_CATEGORY_START";
export const GET_HERO_BY_CATEGORY_SUCCESS = "GET_HERO_BY_CATEGORY_SUCCESS";
export const GET_HERO_BY_CATEGORY_FAIL = "GET_HERO_BY_CATEGORY_FAIL";

export const SELECT_HERO_BY_CATEGORY_START = "SELECT_HERO_BY_CATEGORY_START";
export const SELECT_HERO_BY_CATEGORY_SUCCESS =
  "SELECT_HERO_BY_CATEGORY_SUCCESS";
export const SELECT_HERO_BY_CATEGORY_FAIL = "SELECT_HERO_BY_CATEGORY_FAIL";

// Hero Section by Brands
export const GET_HERO_BY_BRANDS_START = "GET_HERO_BY_BRANDS_START";
export const GET_HERO_BY_BRANDS_SUCCESS = "GET_HERO_BY_BRANDS_SUCCESS";
export const GET_HERO_BY_BRANDS_FAIL = "GET_HERO_BY_BRANDS_FAIL";

export const SELECT_HERO_BY_BRANDS_START = "SELECT_HERO_BY_BRANDS_START";
export const SELECT_HERO_BY_BRANDS_SUCCESS = "SELECT_HERO_BY_BRANDS_SUCCESS";
export const SELECT_HERO_BY_BRANDS_FAIL = "SELECT_HERO_BY_BRANDS_FAIL";

// Hero Section by Models
export const GET_HERO_BY_MODELS_START = "GET_HERO_BY_MODELS_START";
export const GET_HERO_BY_MODELS_SUCCESS = "GET_HERO_BY_MODELS_SUCCESS";
export const GET_HERO_BY_MODELS_FAIL = "GET_HERO_BY_MODELS_FAIL_FAIL";

export const SELECT_HERO_BY_MODELS_START = "SELECT_HERO_BY_MODELS_START";
export const SELECT_HERO_BY_MODELS_SUCCESS = "SELECT_HERO_BY_MODELS_SUCCESS";
export const SELECT_HERO_BY_MODELS_FAIL = "SELECT_HERO_BY_MODELS_FAIL_FAIL";


// USER AUTHENTICATION 
export const REG_CHECK_START = "REG_CHECK_START"
export const REG_CHECK_SUCCESS = "REG_CHECK_SUCCESS"
export const REG_CHECK_FAIL = "REG_CHECK_FAIL"

export const REG_OTP_START = "REG_OTP_START"
export const REG_OTP_SUCCESS = "REG_OTP_SUCCESS"
export const REG_OTP_FAIL = "REG_OTP_FAIL"

export const REG_USER_START = "REG_USER_START"
export const REG_USER_SUCCESS = "REG_USER_SUCCESS"
export const REG_USER_FAIL = "REG_USER_FAIL"

export const LOGIN_OTP_START = "LOGIN_OTP_START"
export const LOGIN_OTP_SUCCESS = "LOGIN_OTP_SUCCESS"
export const LOGIN_OTP_FAIL = "LOGIN_OTP_FAIL"

export const LOGIN_USER_START = "LOGIN_USER_START"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const LOGOUT_USER_START = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER"

export const USER_ACTION_SUGGESTION = "USER_ACTION_SUGGESTION"
export const USER_CLEAR = "USER_CLEAR"