// Home Page

// Testimonials Home
export const GET_HOME_TESTIMONIALS = "GET_HOME_TESTIMONIALS";
export const GET_HOME_TESTIMONIALS_FAIL = "GET_HOME_TESTIMONIALS_FAIL";

// Hero Section Home
export const GET_HOME_HERO_SECTION = "GET_HOME_HERO_SECTION";
export const GET_HOME_HERO_SECTION_FAIL = "GET_HOME_HERO_SECTION_FAIL";

// home appliances
export const GET_HOME_APPLIANCES = "GET_HOME_APPLIANCES";
export const SELECT_HOME_APPLIANCES = "SELECT_HOME_APPLIANCES";
export const GET_HOME_APPLIANCES_FAIL = "SELECT_HOME_APPLIANCES_FAIL";

// home appliances models
export const GET_HOME_APPLIANCES_MODELS = "GET_HOME_APPLIANCES_MODELS";
export const SELECT_HOME_APPLIANCES_MODELS = "SELECT_HOME_APPLIANCES_MODELS";
export const GET_HOME_APPLIANCES_MODELS_FAIL =
  "SELECT_HOME_APPLIANCES_MODELS_FAIL";

//home appliances issues
export const GET_HOME_APPLIANCES_ISSUES = "GET_HOME_APPLIANCES_ISSUES";
export const SELECT_HOME_APPLIANCES_ISSUES = "SELECT_HOME_APPLIANCES_ISSUES";
export const GET_HOME_APPLIANCES_ISSUES_FAIL =
  "SELECT_HOME_APPLIANCES_ISSUES_FAIL";

// personal gadgets
export const GET_PERSONAL_GADGETS = "GET_PERSONAL_GADGETS";
export const SELECT_PERSONAL_GADGETS = "SELECT_PERSONAL_GADGETS";
export const GET_PERSONAL_GADGETS_FAIL = "SELECT_PERSONAL_GADGETS_FAIL";

// Personal Brands
export const GET_PERSONAL_BRANDS = "GET_PERSONAL_BRANDS";
export const SELECT_PERSONAL_BRANDS = "SELECT_PERSONAL_BRANDS";
export const GET_PERSONAL_BRANDS_FAIL = "SELECT_PERSONAL_BRANDS_FAIL";

// Personal Models
export const GET_PERSONAL_MODELS = "GET_PERSONAL_MODELS";
export const SELECT_PERSONAL_MODELS = "SELECT_PERSONAL_MODELS";
export const GET_PERSONAL_MODELS_FAIL = "SELECT_PERSONAL_MODELS_FAIL";

//personal issues
export const GET_PERSONAL_GADGETS_ISSUES = "GET_PERSONAL_GADGETS_ISSUES";
export const SELECT_PERSONAL_GADGETS_ISSUES = "SELECT_PERSONAL_GADGETS_ISSUES";
export const GET_PERSONAL_GADGETS_ISSUES_FAIL =
  "SELECT_PERSONAL_GADGETS_ISSUES_FAIL";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

// Login
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_IN_FAIL = "USER_LOGGED_IN_FAIL";

// Coupons
export const GET_VALID_COUPONS = "GET_VALID_COUPONS";
export const APPLY_COUPONS = "APPLY_COUPONS";
export const REMOVE_COUPONS = "REMOVE_COUPONS";
export const GET_COUPONS_FAIL = "REMOVE_COUPONS_FAIL";

// Offers
export const GET_OFFERS_HOME = "GET_OFFERS_HOME";
export const SELECT_OFFERS_HOME = "SELECT_OFFERS_HOME";
export const GET_OFFERS_HOME_FAIL = "SELECT_OFFERS_HOME_FAIL";

// Offers by Category
export const GET_OFFERS_BY_CATEGORY = "GET_OFFERS_HOME";
export const SELECT_OFFERS_BY_CATEGORY = "SELECT_OFFERS_HOME";
export const GET_OFFERS_BY_CATEGORY_FAIL = "SELECT_OFFERS_HOME_FAIL";

// Offers by Brands
export const GET_OFFERS_BY_BRANDS = "GET_OFFERS_BY_BRANDS";
export const SELECT_OFFERS_BY_BRANDS = "SELECT_OFFERS_BY_BRANDS";
export const GET_OFFERS_BY_BRANDS_FAIL = "SELECT_OFFERS_BY_BRANDS_FAIL";

// Offers by Models
export const GET_OFFERS_BY_MODELS = "GET_OFFERS_BY_MODELS";
export const SELECT_OFFERS_BY_MODELS = "SELECT_OFFERS_BY_MODELS";
export const GET_OFFERS_BY_MODELS_FAIL = "SELECT_OFFERS_BY_MODELS_FAIL";

// Info by Category
export const GET_INFORMATION_BY_CATEGORY = "GET_INFORMATION_BY_CATEGORY";
export const SELECT_INFORMATION_BY_CATEGORY = "SELECT_INFORMATION_BY_CATEGORY";
export const GET_INFORMATION_BY_CATEGORY_FAIL =
  "SELECT_INFORMATION_BY_CATEGORY_FAIL";

// Info by Brands
export const GET_INFORMATION_BY_BRANDS = "GET_INFORMATION_BY_BRANDS";
export const SELECT_INFORMATION_BY_BRANDS = "SELECT_INFORMATION_BY_BRANDS";
export const GET_INFORMATION_BY_BRANDS_FAIL =
  "SELECT_INFORMATION_BY_BRANDS_FAIL";

// Info by Models
export const GET_INFORMATION_BY_MODELS = "GET_INFORMATION_BY_MODELS";
export const SELECT_INFORMATION_BY_MODELS = "SELECT_INFORMATION_BY_MODELS";
export const GET_INFORMATION_BY_MODELS_FAIL =
  "SELECT_INFORMATION_BY_MODELS_FAIL";

// FAQ by Category
export const GET_FAQ_BY_CATEGORY = "GET_FAQ_BY_CATEGORY";
export const GET_FAQ_BY_CATEGORY_FAIL = "SELECT_FAQ_BY_CATEGORY_FAIL";

// FAQ BY Brands
export const GET_FAQ_BY_BRANDS = "GET_FAQ_BY_BRANDS";
export const GET_FAQ_BY_BRANDS_FAIL = "SELECT_FAQ_BY_BRANDS_FAIL";

// FAQ BY Models
export const GET_FAQ_BY_MODELS = "GET_FAQ_BY_MODELS";
export const GET_FAQ_BY_MODELS_FAIL = "SELECT_FAQ_BY_MODELS_FAIL";

// Testimonials by Category
export const GET_TESTIMONIALS_BY_CATEGORY = "GET_TESTIMONIALS_BY_CATEGORY";
export const SELECT_TESTIMONIALS_BY_CATEGORY =
  "SELECT_TESTIMONIALS_BY_CATEGORY";
export const GET_TESTIMONIALS_BY_CATEGORY_FAIL =
  "GET_TESTIMONIALS_BY_CATEGORY_FAIL_FAIL";

// Testimonials by Brands
export const GET_TESTIMONIALS_BY_BRANDS = "GET_TESTIMONIALS_BY_BRANDS";
export const SELECT_TESTIMONIALS_BY_BRANDS = "SELECT_TESTIMONIALS_BY_BRANDS";
export const GET_TESTIMONIALS_BY_BRANDS_FAIL =
  "SELECT_TESTIMONIALS_BY_BRANDS_FAIL";

// Testimonials by Models
export const GET_TESTIMONIALS_BY_MODELS = "GET_TESTIMONIALS_BY_MODELS";
export const SELECT_TESTIMONIALS_BY_MODELS = "SELECT_TESTIMONIALS_BY_MODELS";
export const GET_TESTIMONIALS_BY_MODELS_FAIL =
  "SELECT_TESTIMONIALS_BY_MODELS_FAIL";

// Hero Section by Category
export const GET_HERO_BY_CATEGORY = "GET_HERO_BY_CATEGORY";
export const SELECT_HERO_BY_CATEGORY = "SELECT_HERO_BY_CATEGORY";
export const GET_HERO_BY_CATEGORY_FAIL = "SELECT_HERO_BY_CATEGORY_FAIL";

// Hero Section by Brands
export const GET_HERO_BY_BRANDS = "GET_HERO_BY_BRANDS";
export const SELECT_HERO_BY_BRANDS = "SELECT_HERO_BY_BRANDS";
export const GET_HERO_BY_BRANDS_FAIL = "SELECT_HERO_BY_BRANDS_FAIL";

// Hero Section by Models
export const GET_HERO_BY_MODELS = "GET_HERO_BY_MODELS";
export const SELECT_HERO_BY_MODELS = "SELECT_HERO_BY_MODELS";
export const GET_HERO_BY_MODELS_FAIL = "GET_HERO_BY_MODELS_FAIL_FAIL";
