// Home Page

// city
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAIL = "GET_CITY_FAIL";

// Testimonials Home
export const GET_HOME_TESTIMONIALS_SUCCESS = "GET_HOME_TESTIMONIALS_SUCCESS";
export const GET_HOME_TESTIMONIALS_FAIL = "GET_HOME_TESTIMONIALS_FAIL";

// Hero Section Home
export const GET_HOME_HERO_SECTION_SUCCESS = "GET_HOME_HERO_SECTION_SUCCESS";
export const GET_HOME_HERO_SECTION_FAIL = "GET_HOME_HERO_SECTION_FAIL";

// Issue page
export const GET_CATEGORY_ID_SUCCESS = "GET_CATEGORY_ID_SUCCESS";
export const GET_BRAND_ID_SUCCESS = "GET_BRAND_ID_SUCCESS";
export const GET_MODEL_ID_SUCCESS = "GET_MODEL_ID_SUCCESS";

// home appliances
export const GET_HOME_APPLIANCES_SUCCESS = "GET_HOME_APPLIANCES_SUCCESS";
export const SELECT_HOME_APPLIANCES_SUCCESS = "SELECT_HOME_APPLIANCES_SUCCESS";
export const GET_HOME_APPLIANCES_FAIL = "SELECT_HOME_APPLIANCES_FAIL";

// home appliances models
export const GET_HOME_APPLIANCES_MODELS_SUCCESS =
  "GET_HOME_APPLIANCES_MODELS_SUCCESS";
export const SELECT_HOME_APPLIANCES_MODELS_SUCCESS =
  "SELECT_HOME_APPLIANCES_MODELS_SUCCESS";
export const GET_HOME_APPLIANCES_MODELS_FAIL =
  "SELECT_HOME_APPLIANCES_MODELS_FAIL";

//home appliances issues
export const GET_HOME_APPLIANCES_ISSUES_SUCCESS =
  "GET_HOME_APPLIANCES_ISSUES_SUCCESS";
export const SELECT_HOME_APPLIANCES_ISSUES_SUCCESS =
  "SELECT_HOME_APPLIANCES_ISSUES_SUCCESS";
export const GET_HOME_APPLIANCES_ISSUES_FAIL =
  "SELECT_HOME_APPLIANCES_ISSUES_FAIL";

// personal gadgets
export const GET_PERSONAL_GADGETS_SUCCESS = "GET_PERSONAL_GADGETS_SUCCESS";
export const SELECT_PERSONAL_GADGETS_SUCCESS =
  "SELECT_PERSONAL_GADGETS_SUCCESS";
export const GET_PERSONAL_GADGETS_FAIL = "SELECT_PERSONAL_GADGETS_FAIL";

// Personal Brands
export const GET_PERSONAL_BRANDS_SUCCESS = "GET_PERSONAL_BRANDS_SUCCESS";
export const SELECT_PERSONAL_BRANDS_SUCCESS = "SELECT_PERSONAL_BRANDS_SUCCESS";
export const GET_PERSONAL_BRANDS_FAIL = "SELECT_PERSONAL_BRANDS_FAIL";

// Personal Models
export const GET_PERSONAL_MODELS_SUCCESS = "GET_PERSONAL_MODELS_SUCCESS";
export const SELECT_PERSONAL_MODELS_SUCCESS = "SELECT_PERSONAL_MODELS_SUCCESS";
export const GET_PERSONAL_MODELS_FAIL = "SELECT_PERSONAL_MODELS_FAIL";

//personal issues
export const GET_PERSONAL_GADGETS_ISSUES_SUCCESS =
  "GET_PERSONAL_GADGETS_ISSUES_SUCCESS";
export const SELECT_PERSONAL_GADGETS_ISSUES_SUCCESS =
  "SELECT_PERSONAL_GADGETS_ISSUES_SUCCESS";
export const GET_PERSONAL_GADGETS_ISSUES_FAIL =
  "SELECT_PERSONAL_GADGETS_ISSUES_FAIL";

// Cart
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const GET_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

// Login
export const USER_LOGGED_IN_SUCCESS = "USER_LOGGED_IN_SUCCESS";
export const USER_LOGGED_IN_FAIL = "USER_LOGGED_IN_FAIL";

// Coupons
export const GET_VALID_COUPONS_SUCCESS = "GET_VALID_COUPONS_SUCCESS";
export const APPLY_COUPONS_SUCCESS = "APPLY_COUPONS_SUCCESS";
export const REMOVE_COUPONS_SUCCESS = "REMOVE_COUPONS_SUCCESS";
export const GET_COUPONS_FAIL = "REMOVE_COUPONS_FAIL";

// Offers
export const GET_OFFERS_HOME_SUCCESS = "GET_OFFERS_HOME_SUCCESS";
export const GET_OFFERS_HOME_FAIL = "SELECT_OFFERS_HOME_FAIL";

// Offers by Category
export const GET_OFFERS_BY_CATEGORY_SUCCESS = "GET_OFFERS_HOME_SUCCESS";
export const GET_OFFERS_BY_CATEGORY_FAIL = "SELECT_OFFERS_HOME_FAIL";

// Offers by Brands
export const GET_OFFERS_BY_BRANDS_SUCCESS = "GET_OFFERS_BY_BRANDS_SUCCESS";
export const GET_OFFERS_BY_BRANDS_FAIL = "SELECT_OFFERS_BY_BRANDS_FAIL";

// Offers by Models
export const GET_OFFERS_BY_MODELS_SUCCESS = "GET_OFFERS_BY_MODELS_SUCCESS";
export const GET_OFFERS_BY_MODELS_FAIL = "SELECT_OFFERS_BY_MODELS_FAIL";

// Info by Category
export const GET_INFORMATION_BY_CATEGORY_SUCCESS =
  "GET_INFORMATION_BY_CATEGORY_SUCCESS";
export const GET_INFORMATION_BY_CATEGORY_FAIL =
  "SELECT_INFORMATION_BY_CATEGORY_FAIL";

// Info by Brands
export const GET_INFORMATION_BY_BRANDS_SUCCESS =
  "GET_INFORMATION_BY_BRANDS_SUCCESS";
export const GET_INFORMATION_BY_BRANDS_FAIL =
  "SELECT_INFORMATION_BY_BRANDS_FAIL";

// Info by Models
export const GET_INFORMATION_BY_MODELS_SUCCESS =
  "GET_INFORMATION_BY_MODELS_SUCCESS";
export const GET_INFORMATION_BY_MODELS_FAIL =
  "SELECT_INFORMATION_BY_MODELS_FAIL";

// FAQ by Category
export const GET_FAQ_BY_CATEGORY_SUCCESS = "GET_FAQ_BY_CATEGORY_SUCCESS";
export const GET_FAQ_BY_CATEGORY_FAIL = "SELECT_FAQ_BY_CATEGORY_FAIL";

// FAQ BY Brands
export const GET_FAQ_BY_BRANDS_SUCCESS = "GET_FAQ_BY_BRANDS_SUCCESS";
export const GET_FAQ_BY_BRANDS_FAIL = "SELECT_FAQ_BY_BRANDS_FAIL";

// FAQ BY Models
export const GET_FAQ_BY_MODELS_SUCCESS = "GET_FAQ_BY_MODELS_SUCCESS";
export const GET_FAQ_BY_MODELS_FAIL = "SELECT_FAQ_BY_MODELS_FAIL";

// Testimonials by Category
export const GET_TESTIMONIALS_BY_CATEGORY_SUCCESS =
  "GET_TESTIMONIALS_BY_CATEGORY_SUCCESS";
export const GET_TESTIMONIALS_BY_CATEGORY_FAIL =
  "GET_TESTIMONIALS_BY_CATEGORY_FAIL_FAIL";

// Testimonials by Brands
export const GET_TESTIMONIALS_BY_BRANDS_SUCCESS =
  "GET_TESTIMONIALS_BY_BRANDS_SUCCESS";
export const GET_TESTIMONIALS_BY_BRANDS_FAIL =
  "SELECT_TESTIMONIALS_BY_BRANDS_FAIL";

// Testimonials by Models
export const GET_TESTIMONIALS_BY_MODELS_SUCCESS =
  "GET_TESTIMONIALS_BY_MODELS_SUCCESS";
export const GET_TESTIMONIALS_BY_MODELS_FAIL =
  "SELECT_TESTIMONIALS_BY_MODELS_FAIL";

// Hero Section by Category
export const GET_HERO_BY_CATEGORY_SUCCESS = "GET_HERO_BY_CATEGORY_SUCCESS";
export const SELECT_HERO_BY_CATEGORY_SUCCESS =
  "SELECT_HERO_BY_CATEGORY_SUCCESS";
export const GET_HERO_BY_CATEGORY_FAIL = "SELECT_HERO_BY_CATEGORY_FAIL";

// Hero Section by Brands
export const GET_HERO_BY_BRANDS_SUCCESS = "GET_HERO_BY_BRANDS_SUCCESS";
export const SELECT_HERO_BY_BRANDS_SUCCESS = "SELECT_HERO_BY_BRANDS_SUCCESS";
export const GET_HERO_BY_BRANDS_FAIL = "SELECT_HERO_BY_BRANDS_FAIL";

// Hero Section by Models
export const GET_HERO_BY_MODELS_SUCCESS = "GET_HERO_BY_MODELS_SUCCESS";
export const SELECT_HERO_BY_MODELS_SUCCESS = "SELECT_HERO_BY_MODELS_SUCCESS";
export const GET_HERO_BY_MODELS_FAIL = "GET_HERO_BY_MODELS_FAIL_FAIL";
